name: Sync Fork2

on: 
  workflow_dispatch:
  schedule:
  - cron: "30 5,17 * * *"
  
jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Upstream Sync
      # You may pin to the exact commit or the version.
      # uses: aormsby/Fork-Sync-With-Upstream-action@9e2e4fd0829a2fe8ca4b13693faac9230c414d51
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
        # Branch receiving updates from the upstream repo, e.g. => main, master, prod
          target_sync_branch: develop
        # Input for passing secrets.GITHUB_TOKEN when disabling persistent auth in the checkout step
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Upstream repository, e.g. => aormsby/Fork-Sync-With-Upstream-action
          upstream_sync_repo: yearn/yearn-finance-v3
        # Branch to sync from, e.g. => main, master, dev
          upstream_sync_branch: develop
